language: python
python: 3.5
install: "pip install Lektor"
script: "lektor build"
deploy:
    provider: script
    script: "lektor deploy ghpages"
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: master
