language: python
python: 3.5
install: "pip install git+git://github.com/lektor/lektor.git@bb85c95d8dceb326dacca0a577ab81d999dd5297"
script: "lektor build"
deploy:
    provider: script
    script: "lektor deploy ghpages"
    skip_cleanup: true
    # github_token: $GITHUB_TOKEN
    on:
        branch: master
