language: python
python: 3.5
os: linux
dist: xenial
install: "pip install git+https://github.com/lektor/lektor#egg=Lektor"
script: "lektor build"
deploy:
    provider: script
    script: "lektor deploy ghpages"
    cleanup: true
    on:
        branch: deploy 
